repos:
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1  # Укажите актуальную версию
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/psf/black
    rev: 23.1.0  # Укажите актуальную версию
    hooks:
      - id: black
        args: ["--check"]

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1  # Укажите актуальную версию
    hooks:
      - id: flake8

  - repo: https://github.com/python/mypy
    rev: v0.910  # Укажите актуальную версию
    hooks:
      - id: mypy
