name: CI

on:
  push:
    branches:
      - main  # Укажите вашу основную ветку, если она отличается
  pull_request:
    branches:
      - main  # Действия запускаются также для pull request в ветку main

jobs:
  lint:
    name: Code Quality Checks  # Название задания
    runs-on: ubuntu-latest  # Среда выполнения задания

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout code
        uses: actions/checkout@v2
        # Описание: Этот шаг клонирует ваш репозиторий на машину GitHub Actions.

      # Шаг 2: Установка Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'  # Убедитесь, что ваш проект совместим с этой версией Python
        # Описание: Этот шаг устанавливает версию Python, указанную в конфигурации.

      # Шаг 3: Установка зависимостей
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 isort black mypy pre-commit
          pip install pydantic sqlalchemy aiosqlite pytest pytest-asyncio httpx uvicorn fastapi
        # Описание: Этот шаг обновляет pip и устанавливает необходимые зависимости для проекта.

      # Шаг 4: Проверка кода с помощью Flake8
      - name: Run Flake8 (Linting)
        run: flake8 .
        continue-on-error: false  # Прерывает выполнение при ошибках
        # Описание: Этот шаг выполняет линтинг кода с помощью Flake8 и останавливает выполнение при ошибках.

      # Шаг 5: Проверка сортировки импортов с помощью isort
      - name: Run isort (Import Sorting Check)
        run: isort .
        # Описание: Этот шаг проверяет и сортирует импорты в коде с помощью isort.

      # Шаг 6: Проверка форматирования кода с помощью Black
      - name: Run Black (Code Formatting Check)
        run: black .
        # Описание: Этот шаг проверяет форматирование кода с помощью Black.

      # Шаг 7: Статический анализ типов с помощью Mypy
      - name: Run Mypy (Type Checking)
        run: mypy .
        # Описание: Этот шаг выполняет статический анализ типов с помощью Mypy.
